name: apples-server-plugin
version: '${version}'
main: com.apples.ApplesSpigotPlugin
api-version: 1.19
authors: [ ilovapples ]
description: Plugin testing
commands:
  kit:
    description: Gives kit of choice
    usage: /kit <user> <kit>
    permission: apples.kit
  dc:
    description: Sends you the Discord link
    usage: /dc
    permission: apples.dc
  discord:
    description: Sends you the Discord link
    usage: /discord
    permission: apples.dc
